# Generated by Django 4.1.7 on 2023-04-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_author_blog_author_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author_user',
            new_name='author',
        ),
    ]
